
services:
  db: 
    image: postgres:14-alpine 
    container_name: my_project_db # имя контейнера
    restart: always 
    environment: 
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      # чтобы можно было подключаться к БД с компьютера
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: